Refactor/change format of generated typescript from resource store
cccteam/ccc pull request #119
Opened 2024-11-07 23:04 UTC by jrowland-ccc

Updates the typescript generation template to desired format.

Also refactors the methods associated with typescript template rendering: 

- Map types like `map[string]accesstypes.Resource` can be replaced with `map[accesstypes.Resource]struct{}` for reduced memory usage and simpler typing. 
- Removed conversions of `accesstypes.Resource` to `string` because the type is already an alias of `string`.  
- Removed `fmt.Sprintf("%s_%s", resource, tag)` occurrences to leverage `ResourceWithTag(tag)` method built into the `accesstypes.Resource` type. 
- Some maps were created with make or composite literals side-by-side, I tried to make it more uniform where I could. 
- I moved some duplicate loops into a nested function within `permissionResources` method, with the hope it improves readability, but it's not strictly necessary.

2024-11-12 20:28 UTC, bswaney-ccc commented on resourcestore/generate_typescript_test.go
> +	t.Helper()
Nice attention to detail!

2024-11-13 15:30 UTC, bswaney-ccc commented on resourcestore/generate_typescript_test.go
> +}
or even something like this
```go
func fakeStores(t *testing.T) fields {
	t.Helper()

	return fields{
		map[accesstypes.PermissionScope]tagStore{
			"global": {
				"Prototype1": {
					"id":       []accesstypes.Permission{"Create", "Delete"},
					"protocol": []accesstypes.Permission{"Create", "Delete"},
				},
				"Prototype2": {
					"id":   []accesstypes.Permission{"Create", "Delete"},
					"uuid": []accesstypes.Permission{"List", "Read", "Update", "Delete"},
					"addr": []accesstypes.Permission{"Create", "Delete"},
				},
				"Prototype3": {
					"socket":  []accesstypes.Permission{},
					"sockopt": []accesstypes.Permission{"Read", "List"},
				},
			},
		},
		map[accesstypes.PermissionScope]resourceStore{
			"global": {
				"Prototype1": {"Create", "Delete"},
				"Prototype2": {"Update", "List", "Read"},
				"Prototype3": {"Delete", "Read", "List"},
			},
		},
	}
}

```

2024-11-13 16:25 UTC, bswaney-ccc commented on resourcestore/generate_typescript_test.go
> +		fields   fields
We should add `t.Parallel()` to the top of this test.

2024-11-13 16:30 UTC, bswaney-ccc commented on resourcestore/generate_typescript.go
>  	}
Our pattern is to wrap the errors that are coming out of external packages, with the function name. 

This is the typical pattern:
```go
	if err := tsFile.Execute(f, TSGenerator{
		Permissions:         s.permissions(),
		Resources:           s.resources(),
		ResourceTags:        s.tags(),
		ResourcePermissions: s.resourcePermissions(),
	}); err != nil {
		return errors.Wrap(err, "template.Template.Execute()")
	}
```

2024-11-13 16:31 UTC, bswaney-ccc commented on resourcestore/generate_typescript.go
>  	if err := f.Close(); err != nil {
Likewise these errors should be wrapped.

2024-11-13 16:34 UTC, bswaney-ccc requested changes
I am finding a lot of linter type errors in this PR, we should make sure that your linter is enable correctly. I requested a few of the changes, but the others will show up automatically, once we get it enabled.

2024-11-13 20:00 UTC, bswaney-ccc commented on resourcestore/generate_typescript.go
>  	return err
This err still needs wrapped

2024-11-13 20:06 UTC, bswaney-ccc commented on resourcestore/generate_typescript.go
>  }
I think we should add some whitespace between the major sections.

suggested:
```
{{- $permissions := .Permissions }}
{{- $resources := .Resources}}
{{- $resourcetags := .ResourceTags }}
{{- $resourcePerms := .ResourcePermissions}}
export enum Permissions {
{{- range $permissions}}
	{{.}} = '{{.}}',
{{- end}}
}

export enum Resources {
{{- range $resource := $resources}}
	{{$resource}} = '{{$resource}}',
{{- end}}
}

{{- range $resource, $tags := $resourcetags}}
export enum {{$resource}} {
	{{- range $_, $tag:= $tags}}
	{{$tag}} = '{{$resource.ResourceWithTag $tag}}',
	{{- end}}
}
{{- end}}

type AllResources = Resources {{- range $resource := .Resources}} | {{$resource}}{{- end}};
type PermissionResources = Record<Permissions, boolean>;
type PermissionMappings = Record<AllResources, PermissionResources>;

const Mappings: PermissionMappings = {
	{{- range $resource := $resources}}
	[Resources.{{$resource}}]: {
		{{- range $perm := $permissions}}
		[Permissions.{{$perm}}]: {{- index $resourcePerms $resource $perm}},
		{{- end}}
	},
		{{- range $tag := index $resourcetags $resource}}
	[{{$resource.ResourceWithTag $tag}}]: {
			{{- range $perm := $permissions}}
		[Permissions.{{$perm}}]: {{- index $resourcePerms ($resource.ResourceWithTag $tag) $perm}},
			{{- end}}
	},
		{{- end}}
	{{- end}}
};

export function requiresPermission(resource: AllResources, permission: Permissions): boolean {
	return Mappings[resource][permission];
}
```

2024-11-15 23:56 UTC, jwatson-ccc approved these changes
LGTM

2024-11-15 23:57 UTC, bswaney-ccc approved these changes
LGTM

2024-11-15 23:59 UTC, merged